module.exports = [
  {
    browserName: "Chrome",
    browser_version: "77.0",
    os: "Windows",
    os_version: "10",
  },
  {
    browserName: "Firefox",
    browser_version: "69.0",
    os: "Windows",
    os_version: "10",
  },
  {
    browserName: "Safari",
    browser_version: "12.1",
    os: "OS X",
    os_version: "Mojave",
  },
  {
    browserName: "Edge",
    browser_version: "18.0",
    os: "Windows",
    os_version: "10",
  },
  {
    browserName: "IE",
    browser_version: "11.0",
    os: "Windows",
    os_version: "10",
  },
  {
    browserName: "IE",
    browser_version: "10.0",
    os: "Windows",
    os_version: "8",
  },
  {
    browserName: "Mobile Safari",
    device: "iPhone 8",
    os: "ios",
    os_version: "12.1",
    real_mobile: true,
  },
  {
    browserName: "Mobile Safari",
    device: "iPhone 6",
    os: "ios",
    os_version: "11.4",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Samsung Galaxy S9 Plus",
    os: "android",
    os_version: "9.0",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Samsung Galaxy S9",
    os: "android",
    os_version: "8.0",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Samsung Galaxy S8",
    os: "android",
    os_version: "7.0",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Samsung Galaxy S7",
    os: "android",
    os_version: "6.0",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Google Nexus 9",
    os: "android",
    os_version: "5.1",
    real_mobile: true,
  },
  {
    browserName: "Android",
    device: "Google Nexus 5",
    os: "android",
    os_version: "4.4",
    real_mobile: true,
  },
];
